# Generated by Django 5.0.2 on 2025-05-12 20:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_delete_question"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizresponse",
            name="raffle_tickets",
            field=models.IntegerField(
                default=0, help_text="Number of raffle tickets earned based on score"
            ),
        ),
    ]
