# Generated by Django 5.0.2 on 2025-05-12 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0005_update_raffle_tickets"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresponse",
            name="raffle_tickets",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Number of raffle tickets earned based on score and referrals",
                max_digits=10,
            ),
        ),
    ]
